CREATE TABLE [dbo].[CustOrder]
(
	[CustID] NVARCHAR(10) NOT NULL,
	[ProdID] NVARCHAR(20) NOT NULL,
	[OrderDate] DATE NOT NULL,
	[Quantity] INT NOT NULL,
	[ShipDate] DATE NULL,
	[ShipMode] NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_ORDER PRIMARY KEY (CustID, ProdID, OrderDate),
	CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CustID) REFERENCES Customer(CustID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY (ProdID) REFERENCES Product(ProdID),
	CONSTRAINT FK_ORDER_SHIPPING FOREIGN KEY (ShipMode) REFERENCES Shipping(ShipMode)
)
