CREATE TABLE [dbo].[Customer]
(
	[CustID] NVARCHAR(10) NOT NULL,
	[FullName] NVARCHAR(20) NOT NULL,
	[Country] NVARCHAR(20) NOT NULL,
	[City] NVARCHAR(20) NOT NULL,
	[State] NVARCHAR(15) NOT NULL,
	[PostCode] INT NOT NULL,
	[SegID] INT NOT NULL,
	[Region] NVARCHAR(10) NOT NULL,
	CONSTRAINT PK_CUSTOMER PRIMARY KEY (CustID),
	CONSTRAINT FK_CUSTOMER_SEGMENT FOREIGN KEY (SegID) REFERENCES Segment(SegID), 
	CONSTRAINT FK_CUSTOMER_REGION FOREIGN KEY (Region) REFERENCES Region(Region)
)
